# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.CharField(max_length=255, verbose_name='Identifiant')),
                ('description', models.TextField(verbose_name='Déscription')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('place', models.CharField(max_length=255, verbose_name='Lieu')),
            ],
        ),
    ]
