# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background',
            field=models.ImageField(null=True, upload_to='', verbose_name='Arrière plan'),
        ),
    ]
