# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shortDescription',
            field=models.CharField(default='Lorem lipsum dolor si amet', max_length=255, verbose_name='Courte description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.ImageField(null=True, upload_to='eventsBackgrounds/', verbose_name='Arrière plan'),
        ),
    ]
