# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160209_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='eventsBackgrounds/', verbose_name='Arrière plan'),
        ),
    ]
