# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160212_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name=b'Evenement associ\xc3\xa9'),
        ),
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=b'eventsBackgrounds/', verbose_name=b'Arri\xc3\xa8re plan'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name=b'D\xc3\xa9scription'),
        ),
    ]
