# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160421_1258'),
        ('events', '0009_auto_20160428_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogArticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name=b'Article associ\xc3\xa9'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='authorName',
            field=models.CharField(blank=True, help_text=b"Si l'auteur n'est pas un utilisateur", max_length=255, null=True, verbose_name=b'Nom'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name=b'Evenement associ\xc3\xa9'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name=b'Identifiant'),
        ),
    ]
