# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='slug', max_length=255),
            preserve_default=False,
        ),
    ]
