# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEL', 'delete'), ('ADD', 'add')], max_length=3)),
                ('modification', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Identifiant'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='modification',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article'),
        ),
    ]
