# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20160201_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article'),
        ),
    ]
