# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_redirection'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
