# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_modification_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='article',
        ),
        migrations.DeleteModel(
            name='Modification',
        ),
    ]
