# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Comment'),
        ),
    ]
