# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Message', verbose_name='Message de base'),
        ),
    ]
