# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_auto_20160221_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
