# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0021_auto_20160226_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'wikiMedia/', verbose_name=b'M\xc3\xa9dia')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Nom')),
                ('uploadDate', models.DateTimeField(auto_now_add=True, verbose_name=b"Date d'upload")),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Auteur')),
            ],
        ),
    ]
