# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name=b'Identifiant'),
        ),
    ]
