# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='', max_length=255, verbose_name='Identifiant'),
            preserve_default=False,
        ),
    ]
