# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Clé')),
                ('value', models.CharField(max_length=255, verbose_name='Valeur')),
            ],
        ),
    ]
