# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=255, verbose_name=b'Cl\xc3\xa9'),
        ),
    ]
